---

- name: Test 2008sp2 pagefile bug
  hosts: windows2008sp2
  tasks:
  - win_pagefile:
      drive: c
      automatic: no
      override: yes
      initial_size: 512
      maximum_size: 16000
      state: present
